services:

  postgres:
    image: postgres:16.4
    container_name: recsys_postgres
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - recsys_net

  chroma:
    image: chromadb/chroma:0.6.3
    container_name: recsys_chroma
    restart: unless-stopped

    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - PERSIST_DIRECTORY=/chroma/chroma

    volumes:
      - chroma_data:/chroma/chroma

    healthcheck:
      test: [ "CMD", "curl", "-f", "--silent", "--max-time", "5", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

    networks:
      - recsys_net

  redis:
    image: redis:7-alpine
    container_name: recsys_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - recsys_net

  ml_service:
    image: ghcr.io/yalama34/coursearch/recsys-ml-service:latest

    container_name: recsys_ml_service
    restart: always

    environment:
      # postgres
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      # chroma
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
      # models
      HF_HOME: /models
      TRANSFORMERS_CACHE: /models
      SENTENCE_TRANSFORMERS_HOME: /models
      #LLM
      LLM_BASE_URL: ${LLM_BASE_URL}
      LLM_API_KEY: ${LLM_API_KEY}
      # redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

    volumes:
      - ./data:/data
      - ./apps/ml-service/models:/models

    depends_on:
      postgres:
        condition: service_healthy
      chroma:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

    healthcheck:
      test: ["CMD-SHELL", "curl -f -s -o /dev/null --max-time 5 http://localhost:8001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

    ports:
      - "${ML_PORT}:8001"

    networks:
      - recsys_net

  migration:
    image: ghcr.io/yalama34/coursearch/recsys-core-api:latest

    container_name: recsys_migrations

    command: ./migrate.sh
    restart: "no"

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - recsys_net

  core_api:
    image: ghcr.io/yalama34/coursearch/recsys-core-api:latest

    container_name: recsys_backend
    restart: always

    environment:
      # postgres
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      # chroma
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
      # ml-service
      ML_SERVICE_URL: http://ml_service:8001

    depends_on:
      postgres:
        condition: service_healthy
      chroma:
        condition: service_healthy
      ml_service:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

    ports:
      - "${API_PORT}:8000"

    networks:
      - recsys_net


  frontend:
     image: ghcr.io/yalama34/coursearch/recsys-frontend:latest

     container_name: frontend
     restart: always

     environment:
       - REACT_APP_API_URL=http://core_api:8000
     depends_on:
       - core_api

     ports:
       - "${FRONTEND_PORT}:3000"

     networks:
       - recsys_net

  course_provider:
    build:
      context: ./apps/course-provider
      dockerfile: ./Dockerfile
    container_name: recsys_course_provider
    restart: always

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      STEPIK_CLIENT_ID: ${STEPIK_CLIENT_ID}
      STEPIK_CLIENT_SECRET: ${STEPIK_CLIENT_SECRET}
      ENABLED_PROVIDERS: ${ENABLED_PROVIDERS}

    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

    healthcheck:
      test: ["CMD-SHELL", "curl -f -s -o /dev/null --max-time 5 http://localhost:8002/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    networks:
      - recsys_net


volumes:
  postgres_data:
  chroma_data:
  

networks:
  recsys_net:
    driver: bridge
