name: Build

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      # Detect changes
      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            core:
              - 'apps/core-api/**'

            ml:
              - 'apps/ml-service/**'
              - '!apps/ml-service/requirements.txt'

            ml_base:
              - 'apps/ml-service/requirements.txt'

            frontend:
              - 'apps/frontend/**'

      # Login GHCR
      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Set tags
      - name: Set image tags
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          SAFE_BRANCH=$(echo "$BRANCH" | sed 's/\//-/g')

          if [ "$BRANCH" = "main" ]; then
            TAG=latest
          elif [ "$BRANCH" = "develop" ]; then
            TAG=develop
          else
            TAG="$SAFE_BRANCH"
          fi

          SHA_TAG="${TAG}-${GITHUB_SHA}"

          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "SHA_TAG=$SHA_TAG" >> $GITHUB_ENV

      # ML BASE
      - name: Build ML base
        if: steps.filter.outputs.ml_base == 'true' && (github.ref_name == 'main' || github.ref_name == 'develop')
        run: |
          docker build -f apps/ml-service/Dockerfile.base \
            -t ghcr.io/${{ github.repository }}/recsys-ml-base:$TAG \
            ./apps/ml-service
          docker push ghcr.io/${{ github.repository }}/recsys-ml-base:$TAG

      # ML SERVICE
      - name: Build ML service
        if: steps.filter.outputs.ml == 'true' || steps.filter.outputs.ml_base == 'true'
        run: |
          docker build -t ghcr.io/${{ github.repository }}/recsys-ml-service:$TAG \
            -t ghcr.io/${{ github.repository }}/recsys-ml-service:$SHA_TAG \
            ./apps/ml-service

          if [[ "${GITHUB_REF#refs/heads/}" == "main" || "${GITHUB_REF#refs/heads/}" == "develop" ]]; then
            docker push ghcr.io/${{ github.repository }}/recsys-ml-service:$TAG
            docker push ghcr.io/${{ github.repository }}/recsys-ml-service:$SHA_TAG
          fi

      # CORE API
      - name: Build core-api
        if: steps.filter.outputs.core == 'true'
        run: |
          docker build -t ghcr.io/${{ github.repository }}/recsys-core-api:$TAG \
            -t ghcr.io/${{ github.repository }}/recsys-core-api:$SHA_TAG \
            ./apps/core-api

          if [[ "${GITHUB_REF#refs/heads/}" == "main" || "${GITHUB_REF#refs/heads/}" == "develop" ]]; then
            docker push ghcr.io/${{ github.repository }}/recsys-core-api:$TAG
            docker push ghcr.io/${{ github.repository }}/recsys-core-api:$SHA_TAG
          fi

      # FRONTEND
      - name: Build frontend
        if: steps.filter.outputs.frontend == 'true'
        run: |
          docker build -t ghcr.io/${{ github.repository }}/recsys-frontend:$TAG \
            -t ghcr.io/${{ github.repository }}/recsys-frontend:$SHA_TAG \
            ./apps/frontend

          if [[ "${GITHUB_REF#refs/heads/}" == "main" || "${GITHUB_REF#refs/heads/}" == "develop" ]]; then
            docker push ghcr.io/${{ github.repository }}/recsys-frontend:$TAG
            docker push ghcr.io/${{ github.repository }}/recsys-frontend:$SHA_TAG
          fi